intake/urls.py
from django.urls import path

from .views import AOPCoreAbuserView, AOPCoreReportView, AOPCoreWorkPlaceView, Index, thanks

urlpatterns = [
    path('', Index.index, name='index'),
    path('aop-abuser/', AOPCoreAbuserView.abuser, name="AOPCoreAbuser"),
    path('aop-report/', AOPCoreReportView.report, name="AOPCoreReport"),
    path('aop-workplace/', AOPCoreWorkPlaceView.workplace, name="AOPCoreWorkplace"),
    path('thanks/', thanks.thanks, name="thanks"),
]

sitedj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('intake/', include('intake.urls')),
    path('admin/', admin.site.urls),
]

intake/models/AOPCoreAbuser.py
from django.db import models
from django.forms import ModelForm
import django as dj
from django.db.models.signals import post_save
from django.dispatch import receiver
import boto3
import json
import uuid
import intake.utils
from .AOPCoreWorkPlace import WorkPlace
    
# Create your models here.
class Abuser(models.Model):
    class Meta:
        app_label = "intake"
    name = models.CharField(max_length=200)
    occupation = models.CharField(max_length=200)
    workplace = models.CharField(max_length=200, blank=True)
    workplace_choice = models.ForeignKey(WorkPlace, blank=True, on_delete=models.SET_NULL, null=True)
    age = models.IntegerField(blank=True)
    picture = models.URLField(blank=True)
    badgeOr = models.CharField(max_length=50, blank=True)
    approved = models.BooleanField(default=False)
    sid = models.UUIDField(default=uuid.uuid4, editable=False)
    def __str__(self):
        return self.name


@receiver(post_save, sender=Abuser)
def queue_task(sender, instance, created, **kwargs):
    if instance.approved:
        intake.utils.uploadb()

class AbuserForm(ModelForm):
    class Meta:
        model = Abuser
        fields = ["name", "occupation", "workplace", "workplace_choice", "age", "picture", "badgeOr"]

templates/aopcore/abuser.html
{% extends "shared/base.html" %}
{% block head %}
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });

</script>
{% endblock %}
{% block body %}
{% include "aopcore/shared/nav.html" %}
{% if alert %}
<p style="color:red">{{ alert }}</p>
{% endif %}
<form action="/intake/aop-abuser/" method="post">
    {% csrf_token %}
    <input id="name" name="name" type="text" class="validate" required="">
    <label for="name">Name</label>
    <input id="occupation" name="occupation" type="text" class="validate" required="">
    <label for="occupation">Occupation</label>
    <input id="workplace" name="workplace" type="text" class="validate">
    <label for="workplace">Workplace</label>
    <br>
    <h5>Or</h5>
    <br>
    <label for="id_workplace_choice">Workplace Choice</label>
    {{ form.workplace_choice }}
    <input id="age" name="age" type="number" class="validate">
    <label for="age">Age</label>
    <input id="picture" name="picture" type="url" class="validate">
    <label for="picture">Picture (url of picture)</label>
    <input id="badgeOr" name="badgeOr" type="text" class="validate">
    <label for="badgeOr">Badge number or other idetnifying information</label>
    <br>
    <br>
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
    <br />
</form>
{% endblock %}

templates/aopcore/report.html
{% extends "shared/base.html" %}
{% block head %}
<script>
    $(document).ready(function () {
            $('.datepicker').datepicker();
            $('select').formSelect();
        });
</script>
{% endblock %}
{% block body %}
{% include "aopcore/shared/nav.html" %}
{% if alert %}
<p style="color:red">{{ alert }}</p>
{% endif %}
<form action="/intake/aop-report/" method="post">
    {% csrf_token %}
    <input id="abuserName" name="abuserName" type="text" class="validate">
    <label for="abuserName">Abuser Name</label>
    <br>
    <h5>Or</h5>
    <br>
    <label for="abuserChoice">Abuser Choice</label>
    {{ form.abuserChoice }}
    <input id="workplace" name="workplace" type="text" class="validate">
    <label for="workplace">Workplace</label>
    <br>
    <h5>Or</h5>
    <br>
    <label for="workplaceChoice">Workplace Choice</label>
    {{ form.workplaceChoice }}
    <textarea id="fullText" name="fullText" class="materialize-textarea" required=""></textarea>
    <label for="fullText">Full text of report (describe incident/s)</label>
    <input id="typeOf" name="typeOf" type="text" class="validate" required="">
    <label for="typeOf">Type of abuse</label>
    <input type="text" class="datepicker" id="dateOf" name="dateOf" required="">
    <label for="dateOf">Date abuse started/occured</label>
    <br>
    <label>
        <input type="checkbox" id="ongoing" name="ongoing"/>
        <span>Is abuse ongoing?</span>
      </label>
      <br>
      <label>
        <input type="checkbox" id="helpRequested" name="helpRequested"/>
        <span>Do you need help?</span>
      </label>
      <br>
      <input id="typeHelpRequested" name="typeHelpRequested" type="text" class="validate">
      <label for="typeHelpRequested">What type of help do you need?</label>
      <input id="helpComment" name="helpComment" type="text" class="validate">
    <label for="helpComment">Any other comments regarding help?</label>
    <input id="contactEmail" name="contactEmail" type="text" class="validate">
    <label for="contactEmail">Contact email (we will only contact you if you requested help)</label>
    <textarea id="donationDetails" name="donationDetails" class="materialize-textarea"></textarea>
    <label for="donationDetails">Details on where to donate if you requested donations</label>
    <br>
    <br>
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
    <br />
</form>
{% endblock %}

templates/aopcore/workplace.html
{% extends "shared/base.html" %}
{% block body %}
{% include "aopcore/shared/nav.html" %}
    <form action="/intake/aop-workplace/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
        <br/>
    </form>
{% endblock %}